a=23
print(type(a))
a=3.6799
print(type(a))
a=2+4j
print(type(a))
a="string"
print(type(a))
a=[2,4,5,'sd',4.566]
print(type(a))
a=('sdf',3,5.988)
print(type(a))
a={1,3,67,'fg'}
print(type(a))
a={'name':'ram','age':23}
print(type(a))
a=False
print(type(a))
a=bytes(78)
print(type(a))