def add(x,y):
    return x+y
def sub(x,y):
    return x-y
def mul(x,y):
    return x*y
def div(x,y):
    return x//y
def moddiv(x,y):
    return x%y
def square(x):
    return x*x
def cube(x):
    return x*x*x